763 rmc 115 generate initial
ONSdigital/census-rm-actionexporter-service pull request #15
Opened 2019-06-05 08:25 UTC by LukeLoze1

# Motivation and Context

Shared templates for England, Wales and NI

# What has changed
Deleted old templates and mapping, added new ones.  Added new packcode column, this is populated when the ActionRequests are first processed on to the database, they are then referenced in the templates, previously were hardcoded

# How to test?
mvn clean install
run with ATs . with correct actionscheduler installed

# Links
https://trello.com/c/ZmGZEf9A/763-rmc-115-action-exporter-to-generate-initial-contact-print-files-13
https://github.com/ONSdigital/census-rm-action-scheduler/pull/11

2019-06-05 08:46 UTC, NickGrantONS commented on src/main/java/uk/gov/ons/ctp/response/action/export/service/ActionExportService.java
> +          put("ICL4E", "P_IC_ICL4");
Change `ICL4E` to `ICL4N`

2019-06-05 08:47 UTC, NickGrantONS commented on src/main/resources/database/changes/release-22/add_contact_details_in_wales_template.sql
> +
why the blank lines?

2019-06-05 08:47 UTC, NickGrantONS commented on src/main/resources/database/changes/release-23/initial_contact_and_questionaire_template.sql
> +('ICL4E','initial_contact', 'P_IC_ICL4', now(), 'print_service');
Change to `ICL4N`

2019-06-05 08:48 UTC, NickGrantX requested changes
Some `ICL4E`s need changing to `ICL4N`

2019-06-06 09:21 UTC, NickGrantONS commented on src/test/java/uk/gov/ons/ctp/response/action/export/service/ActionExportServiceTest.java
> +    // Then
This is more of a "when"

2019-06-06 09:22 UTC, NickGrantONS commented on src/test/java/uk/gov/ons/ctp/response/action/export/service/ActionExportServiceTest.java
> +    assertTrue(true);
This is the "then" and could just be a comment

2019-06-06 09:23 UTC, NickGrantX approved these changes
Very minor changes,... no reason not to approve. Good work 👍

2019-06-06 12:15 UTC, hbrace approved these changes
Very minor comment

2019-06-06 12:15 UTC, hbrace commented on src/main/resources/database/changes/release-23/changelog.yml
> +            comment: remove all mappring and templates
mappring? Typo?

2019-06-06 13:12 UTC, merged